FROM python:3.11-alpine

COPY requirements_*.txt /opt/app/
COPY pytest.ini /opt/app/
COPY tox.ini /opt/app/

WORKDIR /opt/app

RUN pip install --no-cache-dir --root-user-action=ignore -r requirements_dev.txt

ADD src /opt/app/src

ENTRYPOINT ["tox"]
